language: node_js
node_js:
  - stable
env:
   # Extension ID assigned by the Chrome Web Store
  - EXTENSION_ID='000000000000000000000000000000000'
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      tags: true
